# Generated by Django 3.0.2 on 2020-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_update', models.DateTimeField(auto_now=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('hold_date', models.DateField()),
                ('form', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
